# jwt.secret=${JWT_SECRET}
# jwt.expiration-ms=${JWT_EXPIRATION}
# spring.data.mongodb.uri=${MONGO_URI}
# spring.data.mongodb.database=${MONGO_DB}


spring.application.name=DiuVOte
spring.data.mongodb.uri=mongodb+srv://admin:admin@ecomerce.trqyx67.mongodb.net/univ-voting?appName=ecomerce
server.port=9000
jwt.secret=this_is_a_secret_and_long_Ass_SHIT
jwt.expiration-ms=86400000

server.error.include-message=always
server.error.include-binding-errors=always

# application.properties